### ISSUE TITLE
i tried run execute_everything.sh on wsl code but get permission denied in executingalgorithm.py in the file execute_everything.sh

### ISSUE THREAD

**Issue by samarchamas** [kit-algo/LCD-cliques-experiments#1]

**Comment by michitux** [comment]
The code assumes certain paths, in particular where Infomap is installed. Is it possible that in your home directory in WSL, you do not have `Code/infomap/Infomap`? This is in the first lines of `execute_algorithms.py` (lines 16/17 and 23). If this is not the reason, please include the full error you get.

**Comment by samarchamas** [comment]
I Installed InfoMap using pip install infomap but the error in execute_everything.sh , please check on the bellow:
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 11: /home/samar/Project/LCD-cliques-experiments-master/gen_lfr.py: Permission denied
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 12: ./Project/LCD-cliques-experiments-master/gen_ol_lfr.py: Permission denied
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 13: ./Project/LCD-cliques-experiments-master/gen_weighted_lfr.py: Permission denied
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 14: ./Project/LCD-cliques-experiments-master/convert_fb.py: Permission denied
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 15: ./Project/LCD-cliques-experiments-master/convert_fb.py: Permission denied
executing ./Project/LCD-cliques-experiments-master/output_lfr-dj-uw
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 20: ./Project/LCD-cliques-experiments-master/execute_algorithms.py: Permission denied
executing ./Project/LCD-cliques-experiments-master/output_lfr-ol-uw
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 20: ./Project/LCD-cliques-experiments-master/execute_algorithms.py: Permission denied
executing ./Project/LCD-cliques-experiments-master/output_lfr-weighted
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 20: ./Project/LCD-cliques-experiments-master/execute_algorithms.py: Permission denied
executing ./Project/LCD-cliques-experiments-master/output_fb-dorm
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 20: ./Project/LCD-cliques-experiments-master/execute_algorithms.py: Permission denied
executing ./Project/LCD-cliques-experiments-master/output_fb-dorm-year
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 20: ./Project/LCD-cliques-experiments-master/execute_algorithms.py: Permission denied
evaluating ./Project/LCD-cliques-experiments-master/output_lfr-dj-uw
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 26: ./Project/LCD-cliques-experiments-master/evaluate_communities.py: Permission denied
evaluating ./Project/LCD-cliques-experiments-master/output_lfr-ol-uw
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 26: ./Project/LCD-cliques-experiments-master/evaluate_communities.py: Permission denied
evaluating ./Project/LCD-cliques-experiments-master/output_lfr-weighted
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 26: ./Project/LCD-cliques-experiments-master/evaluate_communities.py: Permission denied
evaluating ./Project/LCD-cliques-experiments-master/output_fb-dorm
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 26: ./Project/LCD-cliques-experiments-master/evaluate_communities.py: Permission denied
evaluating ./Project/LCD-cliques-experiments-master/output_fb-dorm-year
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 26: ./Project/LCD-cliques-experiments-master/evaluate_communities.py: Permission denied
mkdir: cannot create directory ‘plots_fb-dorm’: File exists
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 30: ./Project/LCD-cliques-experiments-master/plot.py: Permission denied
mkdir: cannot create directory ‘plots_fb-dorm-year’: File exists
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 33: ./Project/LCD-cliques-experiments-master/plot.py: Permission denied
mkdir: cannot create directory ‘plots_lfr-dj-uw’: File exists
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 36: ./Project/LCD-cliques-experiments-master/plot_lfr.py: Permission denied
mkdir: cannot create directory ‘plots_lfr-ol-uw’: File exists
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 39: ./Project/LCD-cliques-experiments-master/plot_lfr.py: Permission denied
mkdir: cannot create directory ‘plots_lfr-weighted’: File exists
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 42: ./Project/LCD-cliques-experiments-master/plot_lfr.py: Permission denied
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 44: ./Project/LCD-cliques-experiments-master/time_table.py: Permission denied
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 45: ./Project/LCD-cliques-experiments-master/time_table.py: Permission denied
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 48: ./Project/LCD-cliques-experiments-master/summary_table.py: Permission denied
/home/samar/miniconda3/Project/LCD-cliques-experiments-master/execute_everything.sh: line 49: ./Project/LCD-cliques-experiments-master/summary_table_plot.py: Permission denied

**Comment by samarchamas** [comment]
Please check on the bellow:
vscode://vscode.github-authentication/did-authenticate?windowid=1&code=8eb2f33ac80040f169b8&state=0779fc15-e46c-4047-8292-977708a54ae4

**Comment by michitux** [comment]
It looks like all those files lost their execute permission even though they are definitely marked as executable in this repository. Running `chmod +x *.py` in `/home/samar/miniconda3/Project/LCD-cliques-experiments-master/` should fix this.

**Comment by samarchamas** [comment]
thank you it's working fine
